general {
    layout = master
}

master {
    # New windows become the new master
    #new_status = master 
    # Or, if you want new windows to be added to the slave stack:
     new_status = slave
    
    # Optional: Enable to allow multiple master windows
    # allow_small_split = false 
    
    # Optional: Resize the master window (0.0 - 1.0)
    # mfact = 0.55
}


#dwindle {
 #   pseudotile = false 
#}


#master {
#   new_status = master
#}


misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = true 
}
##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}


windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
