source = ~/.config/hypr/window-rules.conf
source = ~/.config/hypr/input-rules.conf
source = ~/.config/hypr/aesthetics.conf
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/variables.conf
