[files]
recent_files=/home/chris/.config/waybar/style.css;/home/chris/.config/waybar/macchiato.css;/home/chris/Downloads/gnome-shell/gnome-shell.css;/home/chris/Rounded-Rectangle-dark-transparent/RR Dark Green Transparent/gnome-shell/gnome-shell.css;
recent_projects=
current_page=2
FILE_NAME_0=0;CSS;0;EUTF-8;1;1;0;%2Fhome%2Fchris%2FRounded-Rectangle-dark-transparent%2FRR%20Dark%20Green%20Transparent%2Fgnome-shell%2Fgnome-shell.css;0;4
FILE_NAME_1=0;CSS;0;EUTF-8;1;1;0;%2Fhome%2Fchris%2FDownloads%2Fgnome-shell%2Fgnome-shell.css;0;4
FILE_NAME_2=0;CSS;0;EUTF-8;1;1;0;%2Fhome%2Fchris%2F.config%2Fwaybar%2Fstyle.css;0;4

[project]
session_file=
project_file_path=/home/chris/projects

[geany]
treeview_position=230
msgwindow_position=368
geometry=26;23;900;600;0;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=-1
position_find_y=-1
position_replace_x=-1
position_replace_y=-1
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
